<a href="https://colab.research.google.com/github/Gangadharpadshetty/-getplaced/blob/main/introductionnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install  numpy


In [2]:
import numpy as np

In [17]:
lst=[[1,2,3],[4,5,6],[7,8,9]]

In [19]:
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
type(lst)

list

In [21]:
arr=np.array(lst)

In [13]:
arr

array([1, 2, 3])

In [22]:
type(arr)

numpy.ndarray

In [23]:
arr.ndim

2

In [24]:
arr.shape

(3, 3)

In [25]:
arr.size

9

In [26]:
arr.dtype

dtype('int64')

In [28]:
zeroes=np.zeros((3,5))

In [29]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
ones=np.ones((6,3))

In [32]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])