<a href="https://colab.research.google.com/github/Gangadharpadshetty/-getplaced/blob/main/numpyluct2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
np.random.random((3,3))

In [ ]:
if np.random.random()>0.5:
  print("run the function")
else:
  print("dont run the functio")

dont run the functio


In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1,7,10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [ ]:
arr=np.random.random((4,3))

In [ ]:
arr=np.reshape(arr,(3,4))

In [ ]:
arr

array([[0.73031066, 0.38099   , 0.38245599, 0.52500458],
       [0.47532752, 0.56681817, 0.90599561, 0.70936692],
       [0.59208219, 0.16897055, 0.77259812, 0.4871278 ]])

In [ ]:
arr.flatten()

array([0.73031066, 0.38099   , 0.38245599, 0.52500458, 0.47532752,
       0.56681817, 0.90599561, 0.70936692, 0.59208219, 0.16897055,
       0.77259812, 0.4871278 ])